export type Project = {
  slug: string; number: string; title: string; type: string; intro: string;
  description: string; challenge: string; solution: string; stack: string[];
  color: string; image?: string; live?: string; liveLabel?: string;
};

export const projects: Project[] = [
  { slug:"velmora", number:"01", title:"Velmora", type:"Premium Shopify theme", intro:"An editorial fashion storefront built for independent labels, boutiques and modern lifestyle brands.", description:"A polished Shopify theme combining expressive art direction with the practical commerce tools merchants need to launch and grow.", challenge:"Create a distinctive luxury experience that remains simple to customize, fast to navigate and persuasive across desktop and mobile.", solution:"A modular Shopify architecture with editorial sections, product discovery, responsive layouts and a focused conversion journey.", stack:["Shopify OS 2.0","Liquid","Responsive design","Fashion commerce","Theme editor"], color:"velmora", image:"/images/velmora/hero.png", live:"/velmora", liveLabel:"Explore Velmora" },
  { slug:"agaloova-chat", number:"01", title:"AGALOOVA Chat", type:"Real-time social platform", intro:"A Moroccan conversation platform designed for private, respectful two-person connections.", description:"A mobile-first chat product with live room occupancy, progressive conversation levels, moderation controls and media-ready architecture.", challenge:"Make entry effortless while keeping conversations private, understandable and safe on phones with limited screen space.", solution:"A room-first flow, clear presence states, two-stage conversations, mutual actions and a Cloudflare-based real-time architecture.", stack:["React","Cloudflare Workers","D1","R2","Responsive UX"], color:"coral", live:"https://chat.agaloova.com", liveLabel:"Open live platform" },
  { slug:"lunara", number:"02", title:"Lunara", type:"Premium Shopify theme", intro:"A refined commerce system for fashion, beauty and modern lifestyle brands.", description:"A complete storefront experience featuring predictive search, quick view, AJAX cart, product galleries and responsive variant selection.", challenge:"Combine a premium editorial look with the practical speed and clarity customers expect from a high-converting store.", solution:"Reusable Shopify sections, consistent interaction patterns, mobile-first product journeys and carefully structured theme documentation.", stack:["Shopify","Liquid","JavaScript","Theme architecture","E-commerce UX"], color:"violet", live:"/sectionforge/lunara-documentation", liveLabel:"Read documentation" },
  { slug:"sectionforge", number:"03", title:"SectionForge", type:"Shopify commerce system", intro:"A flexible Online Store 2.0 foundation built for merchants and theme customization.", description:"A modular Shopify theme with product discovery, reusable sections, responsive navigation, cart tools and documentation.", challenge:"Give merchants flexibility without turning the editor or customer experience into a collection of inconsistent components.", solution:"A shared design system, modular Liquid architecture and predictable controls across desktop and mobile storefronts.", stack:["Shopify OS 2.0","Liquid","CSS","JavaScript","Accessibility"], color:"blue", live:"/sectionforge", liveLabel:"Explore SectionForge" },
  { slug:"agaloova-world", number:"04", title:"AGALOOVA World", type:"Digital brand experience", intro:"An original Moroccan visual universe where culture, romance and storytelling meet.", description:"An immersive bilingual website for Aga and Loova, combining cultural chapters, visual galleries, sound and interaction.", challenge:"Translate a highly visual artistic identity into a website that remains fast, navigable and coherent on every screen.", solution:"A mobile-first narrative structure, bold image presentation, focused cultural pages and restrained motion that supports the art.", stack:["Next.js","Responsive UI","Art direction","Interaction design"], color:"emerald", image:"/agaloova-home.png", live:"https://agaloova.com", liveLabel:"Visit website" },
  { slug:"charmox", number:"05", title:"CHARMOX", type:"Shopify fashion store", intro:"A Moroccan streetwear brand shaped around freedom, road trips and the Atlantic coast.", description:"A complete store developed from brand concept to product presentation, responsive storefront and launch-ready commerce.", challenge:"Build a credible fashion experience that carries a young Moroccan identity while keeping product buying simple.", solution:"Clear collection architecture, consistent product storytelling, mobile commerce priorities and a focused visual language.", stack:["Shopify","E-commerce","Branding","Conversion UX"], color:"sand", image:"/images/charmox-home.png", live:"https://charmox.com", liveLabel:"Visit store" },
  { slug:"maria-naqach", number:"06", title:"Maria Naqach", type:"Full-stack portfolio & CMS", intro:"A premium portfolio platform with a private visual studio for models and creative talent.", description:"A complete model portfolio with live desktop and mobile preview, media management, editable profile details, SEO controls and a protected owner studio.", challenge:"Create a luxurious public portfolio while giving its owner complete control over photos, content, design and publishing without touching code.", solution:"A cinematic responsive website connected to a protected visual CMS with Cloudflare Access, D1 database, R2 media storage and live publishing.", stack:["React","TypeScript","Cloudflare Workers","D1","R2","Visual CMS","Mobile-first"], color:"rose", image:"/images/maria-naqach.jpg", live:"https://maria.agaloova.com", liveLabel:"Open live website" },
];

export const projectBySlug = (slug: string) => projects.find((project) => project.slug === slug)!;


